StateSpaceNetworkSampleType: index
StateSpaceEngineSampleConversion: index_to_dict


ActionSpaceNetworkSampleType: exploration
ActionSpaceEngineSampleConversion: index_to_dict


AgentLearningRate: 0.001
AgentEpochCounter: Counter_1
AgentIterationCounter: Counter_2
AgentIsUpdateNetwork: True


ExplorationMethod: boltzmann
ExplorationBoltzmannProbAttribute: prob_dist
ExplorationCounter: Counter_4
#ExplorationMethod: e_greedy
#ExplorationCounter: Counter_3


AgentModelSaverSavePath: ../SavedModel
AgentModelSaverSaveName: cointegration


AgentModelSaverRestorePath: ../SavedModel
AgentModelSaverRestoreName: cointegration


ExperienceReplay: True
ExperienceBufferBufferSize: 10000
ExperienceBufferSamplingSize: 1
ExperienceReplayFreq: 5


RecorderDataField: [NETWORK_ACTION, ENGINE_REWARD, ENGINE_RECORD]
RecorderRecordFreq: 1


Counter:
  Counter_1:
    name: Epoch
    start_num: 0
    end_num: 3
    #end_num: 1 # MTR (Ref. case)
    step_size: 1
    n_buffer: 0
    is_descend: False
    print_freq: 1
  Counter_2:
    name: Iteration
    start_num: 0
    end_num: 6000
    step_size: 1
    n_buffer: 1000
    is_descend: False
    print_freq: 1000
    
  Counter_3:
    name: EGreedyProb
    start_num: 1
    end_num: 0.01
    step_size: 0.001
    n_buffer: 1000
    is_descend: True
    print_freq: 100
  Counter_4:
    name: BoltzmannTemp
    start_num: 1
    end_num: 0.01
    step_size: 0.001
    n_buffer: 1000
    is_descend: True
    print_freq: 100
